### ISSUE TITLE
One Suggestion

### ISSUE THREAD

**Issue by Bian-Sh** [Hertzole/advanced-level-editor#11]
https://github.com/Hertzole/advanced-level-editor/blob/2f1de801616851c745ddd59031d8ee4005396e43/Packages/se.hertzole.ale/Runtime/Core/LevelEditorObjectManager.cs#L76

maybe you should change the OnDestory Callback to  OnApplicationQuit callback as  Object Instance may destory before LevelEditorObjectManager .

**Comment by Hertzole** [comment]
Hi! The reason it's OnDestroy and not OnApplicationQuit is because it needs to be called when switching scenes.   
Overall, this is a messy system that I haven't had time to fix. Unfortunately, ALE is a bit in maintenance mode I can't refactor this right now, but hopefully, I'll get back to it eventually!

Thank you for your suggestions!

**Comment by Bian-Sh** [comment]
Yeap, I found that ,when unity editor stop play mode will case some null exception,
